version: '2'
services:
  worker-0:
    image: registry.cn-hangzhou.aliyuncs.com/denverdino/tensorflow-worker:0.9.0
    container_name: worker-0
    ports:
      - "8080"
    environment:
      - WORKER_HOSTS=worker-0:8080,worker-1:8080
      - MASTER_HOSTS=master-0:8080
      - JOB_NAME=worker
      - TASK_INDEX=0
  worker-1:
    image: registry.cn-hangzhou.aliyuncs.com/denverdino/tensorflow-worker:0.9.0
    container_name: worker-1
    ports:
      - "8080"
    environment:
      - WORKER_HOSTS=worker-0:8080,worker-1:8080
      - MASTER_HOSTS=master-0:8080
      - JOB_NAME=worker
      - TASK_INDEX=1
  master-0:
    image: registry.cn-hangzhou.aliyuncs.com/denverdino/tensorflow-worker:0.9.0
    container_name: master-0
    ports:
      - "8080"
    environment:
      - WORKER_HOSTS=worker-0:8080,worker-1:8080
      - MASTER_HOSTS=master-0:8080
      - JOB_NAME=master
      - TASK_INDEX=0
